# Predicting Remaining Useful Life (advanced)
<p style="margin:30px">
    <img style="display:inline; margin-right:50px" width=50% src="https://www.featuretools.com/wp-content/uploads/2017/12/FeatureLabs-Logo-Tangerine-800.png" alt="Featuretools" />
    <img style="display:inline" width=15% src="https://upload.wikimedia.org/wikipedia/commons/e/e5/NASA_logo.svg" alt="NASA" />
</p>

This notebook has a more advanced workflow than [the other notebook](Simple%20Featuretools%20RUL%20Demo.ipynb) for predicting Remaining Useful Life (RUL). If you are a new to either this dataset or Featuretools, I would recommend reading the other notebook first. 

## Highlights
* Demonstrate how novel entityset structures improve predictive accuracy
* Build custom primitives using time-series functions from [tsfresh](https://github.com/blue-yonder/tsfresh)
* Improve Mean Absolute Error by tuning hyper parameters with [BTB](https://github.com/HDI-Project/BTB)

Here is a collection of scores from a run of both notebooks. Because of the randomness in the Random Forest Regressor and how we choose labels from the Train data, scores are subject to change.

|                                 | Train |  Test |
|---------------------------------|---------------|
| Median Baseline                 | 62.55 | 50.55 |
| Simple Featuretools             | 41.18 | 39.56 |
| Advanced: Custom Primitives     | 36.46 | 32.60 |
| Advanced: Hyperparameter Tuning | 27.49 | 13.42 |


# Step 1: Load Data
Here we load in the train data using the same function we used in the previous notebook:

In [1]:
import numpy as np
import pandas as pd
import featuretools as ft
import utils

data_path = 'data/RUL_train.txt'
data = utils.load_data(data_path)

data.head()

engine_no  time_in_cycles  operational_setting_1  \
index                                                     
0              1               1                42.0049   
1              1               2                20.0020   
2              1               3                42.0038   
3              1               4                42.0000   
4              1               5                25.0063   

       operational_setting_2  operational_setting_3  sensor_measurement_1  \
index                                                                       
0                     0.8400                  100.0                445.00   
1                     0.7002                  100.0                491.19   
2                     0.8409                  100.0                445.00   
3                     0.8400                  100.0                445.00   
4                     0.6207                   60.0                462.54   

       sensor_measurement_2  sensor_measurement_3  sensor_measurement_4  \
index                                                                     
0                    549.68               1343.43               1112.93   
1                    606.07               1477.61               1237.50   
2                    548.95               1343.12               1117.05   
3                    548.70               1341.24               1118.03   
4                    536.10               1255.23               1033.59   

       sensor_measurement_5         ...          sensor_measurement_14  \
index                               ...                                  
0                      3.91         ...                        8074.83   
1                      9.35         ...                        8046.13   
2                      3.91         ...                        8066.62   
3                      3.91         ...                        8076.05   
4                      7.05         ...                        7865.80   

       sensor_measurement_15  sensor_measurement_16  sensor_measurement_17  \
index                                                                        
0                     9.3335                   0.02                    330   
1                     9.1913                   0.02                    361   
2                     9.4007                   0.02                    329   
3                     9.3369                   0.02                    328   
4                    10.8366                   0.02                    305   

       sensor_measurement_18  sensor_measurement_19  sensor_measurement_20  \
index                                                                        
0                       2212                 100.00                  10.62   
1                       2324                 100.00                  24.37   
2                       2212                 100.00                  10.48   
3                       2212                 100.00                  10.54   
4                       1915                  84.93                  14.03   

       sensor_measurement_21  index                time  
index                                                    
0                     6.3670      0 2000-01-01 00:00:00  
1                    14.6552      1 2000-01-01 00:00:01  
2                     6.4213      2 2000-01-01 00:00:02  
3                     6.4176      3 2000-01-01 00:00:03  
4                     8.6754      4 2000-01-01 00:00:04  

[5 rows x 28 columns]

We also make cutoff times by selecting a random cutoff time from the life of each engine:

In [2]:
cutoff_times = utils.make_cutoff_times(data)

cutoff_times.head()

engine_no         cutoff_time  RUL
index                                    
1              1 2000-01-01 00:04:05   75
2              2 2000-01-01 00:05:43  276
3              3 2000-01-01 00:11:14  252
4              4 2000-01-01 00:19:27   33
5              5 2000-01-01 00:20:30  163

We're going to do something fancy for our entityset. The values for `operational_setting` 1-3 are continuous but create an implicit relation between different engines. If two engines have a similar `operational_setting`, it could indicate that we should expect the sensor measurements to mean similar things. We make clusters of those settings using `KMeans` from scikit-learn and make a new entity from the clusters.

In [3]:
from sklearn.cluster import KMeans

nclusters = 10

def make_entityset(data, nclusters, kmeans=None):
    X = data[['operational_setting_1', 'operational_setting_2', 'operational_setting_3']]
    if kmeans:
        kmeans=kmeans
    else:
        kmeans = KMeans(n_clusters=nclusters).fit(X)
    data['settings_clusters'] = kmeans.predict(X)
    
    es = ft.EntitySet('Dataset')
    es.entity_from_dataframe(dataframe=data,
                             entity_id='recordings',
                             index='index',
                             time_index='time')

    es.normalize_entity(base_entity_id='recordings', 
                        new_entity_id='engines',
                        index='engine_no')
    
    es.normalize_entity(base_entity_id='recordings', 
                        new_entity_id='cycles',
                        index='time_in_cycles')
    
    es.normalize_entity(base_entity_id='recordings', 
                        new_entity_id='settings_clusters',
                        index='settings_clusters')
    
    return es, kmeans
es, kmeans = make_entityset(data, nclusters)
es

Entityset: Dataset
  Entities:
    recordings (shape = [61249, 29])
    cycles (shape = [543, 2])
    settings_clusters (shape = [50, 2])
    engines (shape = [249, 2])
  Relationships:
    recordings.engine_no -> engines.engine_no
    recordings.time_in_cycles -> cycles.time_in_cycles
    recordings.settings_clusters -> settings_clusters.settings_clusters

# Step 2: DFS and Creating a Model
In addition to changing our `EntitySet` structure, we're also going to use some time series primitives from the package [tsfresh](https://github.com/blue-yonder/tsfresh).

In [18]:
from tsfresh.feature_extraction.feature_calculators import number_peaks, mean_abs_change
from featuretools.primitives import make_agg_primitive
import featuretools.variable_types as vtypes

MeanAbsChange = make_agg_primitive(mean_abs_change,
                                   input_types=[vtypes.Numeric],
                                   return_type=vtypes.Numeric,
                                   name="mean_abs_change")

NumPeaks = make_agg_primitive(lambda x: number_peaks(x, 3),
                              input_types=[vtypes.Numeric],
                              return_type=vtypes.Numeric,
                              name="number_peaks")


from featuretools.primitives import Sum, Mean, Std, Skew, Max, Min, Last, CumSum, Diff, Trend, Count
fm, features = ft.dfs(entityset=es, 
                      target_entity='engines',
                      agg_primitives=[Max, Last, NumPeaks],
                      trans_primitives=[],
                      cutoff_time=cutoff_times,
                      max_depth=3,
                      verbose=True)
fm.to_csv('advanced_fm.csv')

Built 510 features
Elapsed: 17:35 | Remaining: 00:00 | Progress: 100%|██████████|| Calculated: 249/249 cutoff times


# Step 3: Feature Selection and Scoring
Here, we'll use [Recursive Feature Elimination](http://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html). In order to set ourselves up for later optimization, we're going to write a generic `pipeline` function which takes in a set of hyperparameters and returns a score. Our pipeline will first run `RFE` and then split the remaining data for scoring by a `RandomForestRegressor`. We're going to pass in a list of hyperparameters, which we will tune later. 

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.feature_selection import RFE

def pipeline(X, y, hyperparams):
    """ Hyperparams: [
            0: number of estimators for the random forest in RFE
            1: number of features to select
            2: number of estimators for  random forest in scoring
            3: max feats for random forest in scoring
        ]
    """
    reg = RandomForestRegressor(n_estimators=int(hyperparams[0]), n_jobs=3)
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    selector = RFE(reg, int(hyperparams[1]), step=50)
    selector = selector.fit(X_train, y_train)
    max_feats = min(hyperparams[3], hyperparams[1])
    reg = RandomForestRegressor(n_estimators=int(hyperparams[2]), 
                                max_features=int(max_feats))
    reg.fit(selector.transform(X_train), y_train)
    
    preds = reg.predict(selector.transform(X_test))
    score = mean_absolute_error(preds, y_test)
    return score, (selector, reg)

fm = pd.read_csv('advanced_fm.csv', index_col='engine_no')
X = fm.copy().fillna(0)
y = X.pop('RUL')

rfe_nest = 50
nfeats = 50
sco_nest = 50
sco_maxfeats = 50

hyperparams = [rfe_nest, nfeats, sco_nest, sco_maxfeats]
score, (selector, model) = pipeline(X, y, hyperparams)

print('Mean Abs Error: {:.2f}'.format(score))
high_imp_feats = utils.feature_importances(X.iloc[:, selector.support_], model, feats=10)

Mean Abs Error: 36.46
1: NUMBER_PEAKS(recordings.settings_clusters.NUMBER_PEAKS(recordings.sensor_measurement_8)) [0.180]
2: MAX(recordings.sensor_measurement_17) [0.094]
3: MAX(recordings.settings_clusters.LAST(recordings.sensor_measurement_11)) [0.061]
4: MAX(recordings.cycles.LAST(recordings.sensor_measurement_17)) [0.056]
5: MAX(recordings.sensor_measurement_13) [0.050]
6: MAX(recordings.settings_clusters.LAST(recordings.sensor_measurement_17)) [0.043]
7: MAX(recordings.settings_clusters.LAST(recordings.sensor_measurement_13)) [0.041]
8: NUMBER_PEAKS(recordings.settings_clusters.NUMBER_PEAKS(recordings.sensor_measurement_2)) [0.031]
9: MAX(recordings.cycles.LAST(recordings.sensor_measurement_13)) [0.028]
10: LAST(recordings.cycles.MAX(recordings.sensor_measurement_13)) [0.023]
-----



Lastly, we can use that selector and regressor to score the test values.

In [20]:
data2 = utils.load_data('data/RUL_test.txt')

es2, _ = make_entityset(data2, nclusters, kmeans=kmeans)
fm2 = ft.calculate_feature_matrix(entityset=es2, features=features, verbose=True)
X = fm2.copy().fillna(0)
y = pd.read_csv('data/RUL_test_truth.txt', sep=' ', header=-1, names=['RUL'], index_col=False)
preds2 = model.predict(selector.transform(X))
print('Mean Abs Error: {:.2f}'.format(mean_absolute_error(preds2, y)))

Elapsed: 00:34 | Remaining: 00:00 | Progress: 100%|██████████|| Calculated: 1/1 cutoff times
Mean Abs Error: 32.60


# Step 4: Hyperparameter Tuning
Because of the way we set up our pipeline, we can use a Gaussian Process to tune the hyperparameters. We will use [BTB](https://github.com/HDI-Project/BTB) from the [HDI Project](https://github.com/HDI-Project). Change to fm_test and es_test

In [21]:
from btb.hyper_parameter import HyperParameter
from btb.tuning.gp import GP
from tqdm import tqdm

def run_btb(X, y, n=30):
    hyperparam_ranges = [
            ('selector_n_estimators', HyperParameter('int', [100, 1000])),
            ('select_n_features', HyperParameter('int', [5, 50])),
            ('model_n_estimators', HyperParameter('int', [100, 500])),
            ('model_max_feats', HyperParameter('int', [5, 20])),
    ]
    tuner = GP(hyperparam_ranges)

    tested_parameters = np.zeros((n, len(hyperparam_ranges)), dtype=object)
    scores = []
    best = 100
    
    print('[sel_n_est, sel_n_feats, model_n_est, model_max_feats]')
    for i in tqdm(range(n)):
        tuner.fit(tested_parameters[:i, :], scores)
        hyperparams = tuner.propose()

        bound = -pipeline(X, y, hyperparams)[0]
        tested_parameters[i, :] = hyperparams
        scores.append(bound)
        if -bound < best:
            best = -bound
            print('{}: New best score of {:.2f}'.format(hyperparams, -bound))
    return tested_parameters, scores

X = fm.copy().fillna(0)
y = X.pop('RUL')

tested_parameters, scores = run_btb(X, y, n=30)

  0%|          | 0/30 [00:00<?, ?it/s]

[sel_n_est, sel_n_feats, model_n_est, model_max_feats]


  3%|▎         | 1/30 [00:45<22:05, 45.72s/it]

[526.  48. 193.  11.]: New best score of 36.22


 13%|█▎        | 4/30 [03:53<25:20, 58.48s/it]

[622.  47. 337.  19.]: New best score of 30.78


 40%|████      | 12/30 [11:06<16:39, 55.51s/it]

[621.  48. 340.  16.]: New best score of 30.44


 90%|█████████ | 27/30 [24:45<02:45, 55.03s/it]

[541.  49. 283.  19.]: New best score of 26.80


100%|██████████| 30/30 [26:50<00:00, 53.69s/it]


In [24]:
hyperparams = [541.,  49., 283.,  19.]
score, (selector, model) = pipeline(X, y, hyperparams)

print('Mean Abs Error on Train: {:.2f}'.format(score))
high_imp_feats = utils.feature_importances(X.iloc[:, selector.support_], model, feats=10)

/Users/featurelabs07/homeenv/lib/python2.7/site-packages/ipykernel_launcher.py:21: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


Mean Abs Error on Train: 27.49
1: MAX(recordings.sensor_measurement_11) [0.164]
2: MAX(recordings.sensor_measurement_13) [0.157]
3: MAX(recordings.sensor_measurement_4) [0.133]
4: MAX(recordings.sensor_measurement_3) [0.056]
5: MAX(recordings.sensor_measurement_8) [0.052]
6: LAST(recordings.cycles.NUMBER_PEAKS(recordings.sensor_measurement_7)) [0.027]
7: LAST(recordings.cycles.NUMBER_PEAKS(recordings.sensor_measurement_21)) [0.019]
8: NUMBER_PEAKS(recordings.operational_setting_1) [0.017]
9: MAX(recordings.sensor_measurement_2) [0.017]
10: NUMBER_PEAKS(recordings.settings_clusters.NUMBER_PEAKS(recordings.sensor_measurement_12)) [0.016]
-----



In [25]:
X = fm2.copy().fillna(0)
y = pd.read_csv('data/RUL_test_truth.txt', sep=' ', header=-1, names=['RUL'], index_col=False)

preds2 = model.predict(selector.transform(X))
score2 = mean_absolute_error(preds2, y)
print('Mean Abs Error on Test: {:.2f}'.format(score2))


Mean Abs Error on Test: 13.42


NUMBER_PEAKS(recordings.sensor_measurement_9)  \
engine_no                                                  
1                                                   40.0   
2                                                    1.0   
3                                                    9.0   
4                                                   33.0   
5                                                    4.0   

           LAST(recordings.sensor_measurement_13)  \
engine_no                                           
1                                         2028.37   
2                                         2028.17   
3                                         2388.08   
4                                         2388.87   
5                                         2388.19   

           NUMBER_PEAKS(recordings.sensor_measurement_11)  \
engine_no                                                   
1                                                    41.0   
2                                                     1.0   
3                                                     8.0   
4                                                    35.0   
5                                                     4.0   

           MAX(recordings.sensor_measurement_17)  \
engine_no                                          
1                                            394   
2                                            392   
3                                            393   
4                                            394   
5                                            395   

           MAX(recordings.sensor_measurement_21)  \
engine_no                                          
1                                        23.5729   
2                                        23.4692   
3                                        23.5523   
4                                        23.4354   
5                                        23.3108   

           NUMBER_PEAKS(recordings.sensor_measurement_19)  \
engine_no                                                   
1                                                     0.0   
2                                                     0.0   
3                                                     0.0   
4                                                     0.0   
5                                                     0.0   

           LAST(recordings.sensor_measurement_20)  \
engine_no                                           
1                                           14.25   
2                                           14.18   
3                                           28.74   
4                                           10.59   
5                                           28.65   

           NUMBER_PEAKS(recordings.sensor_measurement_12)  \
engine_no                                                   
1                                                    38.0   
2                                                     1.0   
3                                                     7.0   
4                                                    33.0   
5                                                     4.0   

           NUMBER_PEAKS(recordings.sensor_measurement_7)  \
engine_no                                                  
1                                                   38.0   
2                                                    1.0   
3                                                    7.0   
4                                                   34.0   
5                                                    3.0   

           LAST(recordings.sensor_measurement_9) ...   \
engine_no                                        ...    
1                                        8012.27 ...    
2                                        8013.20 ...    
3                                        8776.65 ...    
4                                        8365.86 ...    
5                                        8760.96 ...    

           